version: pending.{build}
max_jobs: 10
skip_branch_with_pr: false
skip_commits:
  files:
    - docs/*
    - '**/*.html'
    - 'CHANGELOG.rst'
  message: /^release.*/
skip_tags: true

environment:
  GIT_DAEMON_PATH:   "C:\\Program Files\\Git\\mingw64\\libexec\\git-core"
  CYGWIN_GIT_PATH:   "C:\\cygwin\\bin;%GIT_DAEMON_PATH%"
  CYGWIN64_GIT_PATH: "C:\\cygwin64\\bin;%GIT_DAEMON_PATH%"
  PIPENV_VENV_IN_PROJECT: true
  APPVEYOR_ARTIFACT_UPLOAD_TIMEOUT: 60
  PYTHON: "C:\\Python36-x64"
  PYTHON_VERSION: "3.6"
  PYTHON_ARCH: "64"
  GIT_PATH: "%GIT_DAEMON_PATH%"
  PYPI_PWD:
    secure: sVfnGb1FQyKRJg6kD9c6aQ==
  TWINE_USERNAME:
    secure: X+bBVQdggCzIpfy5LX85tg==
  TWINE_PASSWORD :
    secure: sVfnGb1FQyKRJg6kD9c6aQ==

matrix:
  fast_finish: true

init:
  #- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
        throw "There are newer queued builds for this pull request, failing early." }

  # Check that we have the expected version and architecture for Python
  - set PATH=%PYTHON%;%PYTHON%\Scripts;C:\MinGW\msys\1.0\bin;%PATH%
  - "%PYTHON%/python -V"
  - "%PYTHON%/python -c \"import struct;print(8 * struct.calcsize(\'P\'))\""
  - "pip --version"

  - cmd: echo %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%
  - cmd: echo %APPVEYOR_BUILD_WORKER_IMAGE%


install:
  - choco install md5
  - "%PYTHON%\\python.exe -m pip install --disable-pip-version-check --upgrade pip setuptools"
  - cmd: pip install pipenv
  - cmd: pipenv install . --dev

build_script:
  # - cmd: IF /I "%APPVEYOR_PROJECT_NAME%"=="epab" pipenv run pip install . --no-dependencies
  - cmd: pipenv run safety check --bare
  - cmd: >
    pipenv run flake8 --ignore=D203,E126 --max-line-length=120 --exclude .svn,CVS,.bzr,.hg,.git,__pycache__,
    .tox,__init__.py,build,dist,output,.cache,.hypothesis,./test/*,./.eggs/*, --max-complexity=10
  - cmd: >
    pipenv run pylint ./elib_config --reports=n --ignore=CVS --max-line-length=120 -j 8 --persistent=y
    --init-hook="import sys; sys.path.append('.venv')"
    -d disable=logging-format-interpolation,fixme,backtick,long-suffix,raw-checker-failed,bad-inline-option,
    locally-disabled,locally-enabled,suppressed-message,coerce-method,delslice-method,getslice-method,setslice-method,
    next-method-called,too-many-arguments,too-few-public-methods,reload-builtin,oct-method,hex-method,nonzero-method,
    cmp-method,using-cmp-argument,eq-without-hash,exception-message-attribute,sys-max-int,bad-python3-import,
    logging-format-interpolation,wrong-import-order,logging-fstring-interpolation,
    --evaluation="10.0 - ((float(5 * error + warning + refactor + convention) / statement) * 10)"
    --output-format=text --score=n
  - cmd: pipenv run mypy -p elib_config --ignore-missing-imports
  - cmd: pipenv run python -m pytest test --cov=elib_config --cov-report xml --cov-report html --cov-branch --durations=20 --tb=short --cov-config .coveragerc


#on_finish:
  #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
